training: 
  environment:
    env: ChessMulti-v0
    clip_actions: true
    normalize_actions: true
    disable_env_checking: true
    env_config: 
      render_mode: rgb_array
      dim_x: 8
      dim_y: 8
    render_env: false

  rollouts: 
    num_rollout_workers: 20
    num_envs_per_worker: 20
    rollout_fragment_length: auto
    batch_mode: truncate_episodes
    observation_filter: MeanStdFilter


  debugging: 
    logger_creator: ???
    log_level: INFO


  training:
    gamma: 0.99
    train_batch_size: 1024
    model:
      fcnet_hiddens: [256, 256,256,64]
      fcnet_activation: elu
    optimizer:
      type: adam
        
    use_critic: true
    use_gae: true
    lambda_: 0.92
    kl_coeff: 0.2

    sgd_minibatch_size: 64

    num_sgd_iter: 16

    shuffle_sequences: true

    vf_loss_coeff: 0.5

    entropy_coeff: 0.001

    clip_param: 0.2

    kl_target: 0.01

    
    
    vf_clip_param: 1000.0

  framework:
    framework: torch
    eager_tracing: false

  resources:
    num_gpus: 1
    num_cpus_per_worker: 1
    num_gpus_per_worker: 0